### PR TITLE
[Exercise 5.6] Add test for signup page and improve this test

### PR DESCRIPTION
**Pull request by takuminnnn**
## TODO

- [x] 1. Convert the footer CSS from Listing 5.13 to Listing 5.15 to SCSS by hand
- [x] 2. Add a test that verifies the rendered /signup page has the correct title
- [x] 3. Improve test by using code like Listing 5.37
  - [x] Add `full_title` helper method in application helper
  - [x] Fix a test of `2`

## Completion Conditions

- [x] Pasted TravisCI test
- [x] Get `OK` or `LGTM` from one of rjk

### CODE REVIEW

**Comment by alotofwe** [comment]
LGTM

**Comment by takuminnnn** [comment]
@alotofwe ありがとう! :hammer:

**Comment by hanazuki** [comment]
> improved test of signup page by used helper method
and fixed test of static page by following this

`by using helper method` かな〜

**Comment by takuminnnn** [comment]
@hanazuki 確かに...! あざす!

**Comment by tacahilo** [comment]
>  Get OK or LGTM from one of someone

one of rjk? (someoneだと幅広いかも)

**Comment by takuminnnn** [comment]
@tacahilo 幅広でしたね。次回からちゃんと指定します。

**Pull request merged**
